### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by barmstrong** [SamSaffron/MiniProfiler#175]
We're seeing this on MiniProfiler 0.1.27.

Usually after a longer wait time where the local development server is not running (say overnight) this will crop up the next morning on the first page load:

!! Unexpected error while processing request: No such file or directory - /Users/user/code/project/tmp/miniprofiler/mp_views_3b8d0774d3f759f36dd96f694bb39df4

The local development server then needs to be killed/restarted and all is fine.

Any ideas?

**Comment by mattzollinhofer** [comment]
Looks like this issue is no longer a problem. Seems like it's worth closing now or is unintentional file storage still an issue that's worth looking into?

**Comment by SamSaffron** [comment]
Yeah pretty sure we cleaned this stuff up.
